

Codice generato
from pathlib import Path
base=Path('output/gemini_clone_app_v2')
for p in [base/'app', base/'pages', base/'tests', base/'scripts', base/'data']:
    p.mkdir(parents=True, exist_ok=True)
files={
'pyproject.toml':'''[build-system]\nrequires=["setuptools>=68","wheel"]\nbuild-backend="setuptools.build_meta"\n\n[project]\nname="gemini-clone-app-v2"\nversion="1.0.0"\nrequires-python=">=3.11"\ndependencies=["streamlit>=1.36","pandas>=2.2","numpy>=1.26","yfinance>=0.2.40","plotly>=5.22","APScheduler>=3.10","pyarrow>=16.0","requests>=2.32","scikit-learn>=1.5"]\n''',
'requirements.txt':'streamlit\npandas\nnumpy\nyfinance\nplotly\nAPScheduler\npyarrow\nrequests\nscikit-learn\n',
'README.md':'''# Gemini-like Momentum Portfolio\n\nProduction-oriented Streamlit app for U.S. equities using YFinance, with daily backtesting, forward testing, and weekly universe maintenance.\n\n## Run\n```bash\npip install -r requirements.txt\nstreamlit run app.py\n```\n''',
'.gitignore':'output/\n__pycache__/\n*.pyc\n.venv/\n.cache/\n',
'app.py':'''import streamlit as st\nfrom app.main import render_app\nrender_app()\n''',
'app/__init__.py':'',
'app/config.py':'''from dataclasses import dataclass\n\n@dataclass(frozen=True)\nclass Config:\n    period: str = "5y"\n    min_price: float = 5.0\n    min_avg_dollar_volume: float = 10_000_000\n    max_positions: int = 20\n    rebalance_frequency_days: int = 5\n    score_lookbacks: tuple = (20, 60, 120)\n    qqq_sma_days: int = 200\n    slippage_bps: float = 5.0\n    fee_bps: float = 1.0\n''',
'app/data.py':'''from __future__ import annotations\nimport pandas as pd, requests, yfinance as yf\nfrom functools import lru_cache\n\nEXCHANGE_URLS={\n    "NASDAQ":"https://old.nasdaq.com/screening/companies-by-name.aspx?letter=0&exchange=nasdaq&render=download",\n    "NYSE":"https://old.nasdaq.com/screening/companies-by-name.aspx?letter=0&exchange=nyse&render=download",\n    "AMEX":"https://old.nasdaq.com/screening/companies-by-name.aspx?letter=0&exchange=amex&render=download",\n}\n\n@lru_cache(maxsize=1)\ndef load_universe()->pd.DataFrame:\n    frames=[]\n    headers={"User-Agent":"Mozilla/5.0"}\n    for exch,url in EXCHANGE_URLS.items():\n        r=requests.get(url, headers=headers, timeout=30)\n        r.raise_for_status()\n        df=pd.read_csv(pd.io.common.StringIO(r.text))\n        sym=[c for c in df.columns if c.lower().startswith("symbol")][0]\n        name=[c for c in df.columns if c.lower().startswith("name")][0]\n        out=df[[sym,name]].copy()\n        out.columns=["ticker","name"]\n        out["exchange"]=exch\n        frames.append(out)\n    uni=pd.concat(frames, ignore_index=True).drop_duplicates("ticker")\n    uni=uni[uni["ticker"].str.match(r"^[A-Z0-9\-]+$")].reset_index(drop=True)\n    return uni\n\ndef download_ohlcv(tickers:list[str], period:str="5y"):\n    raw=yf.download(tickers, period=period, auto_adjust=True, group_by="ticker", threads=True, progress=False)\n    if isinstance(raw.columns, pd.MultiIndex):\n        closes={}; volumes={}\n        for t in tickers:\n            if t in raw.columns.get_level_values(0):\n                block=raw[t].dropna(how="all")\n                if not block.empty and "Close" in block and "Volume" in block:\n                    closes[t]=block["Close"]\n                    volumes[t]=block["Volume"]\n        return pd.DataFrame(closes), pd.DataFrame(volumes)\n    return raw[["Close"]].rename(columns={"Close":tickers[0]}), raw[["Volume"]].rename(columns={"Volume":tickers[0]})\n\ndef download_benchmark(symbol:str="QQQ", period:str="5y"):\n    df=yf.download(symbol, period=period, auto_adjust=True, progress=False)\n    return df["Close"].dropna()\n''',
'app/signals.py':'''import numpy as np, pandas as pd\n\ndef _zscore(s):\n    return (s - s.mean()) / (s.std(ddof=0) + 1e-9)\n\ndef compute_features(close: pd.DataFrame, volume: pd.DataFrame)->pd.DataFrame:\n    ret=close.pct_change()\n    features={}\n    for t in close.columns:\n        p=close[t]\n        v=volume[t] if t in volume.columns else pd.Series(index=close.index, dtype=float)\n        df=pd.DataFrame(index=close.index)\n        df["ret_20"]=p.pct_change(20)\n        df["ret_60"]=p.pct_change(60)\n        df["ret_120"]=p.pct_change(120)\n        df["sma_50_diff"]=p/p.rolling(50).mean()-1\n        df["sma_200_diff"]=p/p.rolling(200).mean()-1\n        df["vol_20"]=ret[t].rolling(20).std()*np.sqrt(252) if t in ret else np.nan\n        df["vol_60"]=ret[t].rolling(60).std()*np.sqrt(252) if t in ret else np.nan\n        df["dollar_vol"]=p*v.rolling(20).mean()\n        features[t]=df\n    return {k: v for k, v in features.items()}\n\ndef score_frame(df: pd.DataFrame)->pd.Series:\n    s=0.28*_zscore(df["ret_20"]) + 0.28*_zscore(df["ret_60"]) + 0.14*_zscore(df["ret_120"])\n    s += 0.15*_zscore(df["sma_50_diff"]) + 0.15*_zscore(df["sma_200_diff"])\n    s += -0.10*_zscore(df["vol_20"])\n    s += 0.10*_zscore(np.log1p(df["dollar_vol"]))\n    return s\n''',
'app/regime.py':'''import pandas as pd\n\ndef market_regime(qqq: pd.Series)->pd.Series:\n    sma200=qqq.rolling(200).mean()\n    sma50=qqq.rolling(50).mean()\n    return ((qqq > sma200) & (sma50 > sma200)).astype(int)\n''',
'app/portfolio.py':'''import pandas as pd, numpy as np\n\ndef build_portfolio(scores: pd.DataFrame, regime: pd.Series, max_positions:int=20):\n    weights=[]\n    for dt in scores.index:\n        w=pd.Series(0.0, index=scores.columns)\n        if regime.loc[dt] == 1:\n            top=scores.loc[dt].dropna().sort_values(ascending=False).head(max_positions).index\n            if len(top): w.loc[top]=1/len(top)\n        weights.append(w)\n    return pd.DataFrame(weights, index=scores.index)\n''',
'app/backtest.py':'''import pandas as pd, numpy as np\n\ndef run_backtest(close: pd.DataFrame, weights: pd.DataFrame, slippage_bps=5.0, fee_bps=1.0):\n    rets=close.pct_change().fillna(0)\n    w=weights.reindex(close.index).fillna(0)\n    port=(w.shift(1).fillna(0)*rets).sum(axis=1)\n    turnover=w.diff().abs().sum(axis=1).fillna(0)\n    costs=turnover*(slippage_bps+fee_bps)/10000.0\n    net=port-costs\n    equity=(1+net).cumprod()\n    out=pd.DataFrame({"gross_return":port, "net_return":net, "turnover":turnover, "equity":equity}, index=close.index)\n    return out\n''',
'app/scanner.py':'''import pandas as pd\n\ndef weekly_universe_update(latest_scores: pd.Series, old_universe: list[str], add_quantile=0.80, remove_quantile=0.20):\n    s=latest_scores.dropna().sort_values(ascending=False)\n    add=s[s>=s.quantile(add_quantile)].index.tolist()\n    remove=s[s<=s.quantile(remove_quantile)].index.tolist()\n    updated=[t for t in old_universe if t not in remove] + [t for t in add if t not in old_universe]\n    return updated, add, remove\n''',
'app/storage.py':'''from pathlib import Path\nimport pandas as pd\nBASE=Path("data")\nBASE.mkdir(exist_ok=True)\n\ndef save_df(df: pd.DataFrame, name: str):\n    path=BASE/f"{name}.parquet"\n    df.to_parquet(path)\n    return path\n\ndef load_df(name: str):\n    path=BASE/f"{name}.parquet"\n    return pd.read_parquet(path) if path.exists() else None\n''',
'app/scheduler.py':'''from apscheduler.schedulers.background import BackgroundScheduler\nfrom app.storage import save_df\n\ndef build_scheduler(job_fn):\n    s=BackgroundScheduler(timezone="Europe/Rome")\n    s.add_job(job_fn, "cron", day_of_week="sun", hour=23, minute=0, id="weekly_scan", replace_existing=True)\n    return s\n''',
'app/ui.py':'''import streamlit as st, plotly.graph_objects as go\n\ndef render(results, weights, universe, add, remove):\n    st.title("Gemini-like Momentum Portfolio")\n    c1,c2,c3,c4=st.columns(4)\n    c1.metric("Universe", len(universe))\n    c2.metric("Added", len(add))\n    c3.metric("Removed", len(remove))\n    c4.metric("Final positions", int((weights.iloc[-1]>0).sum()))\n    fig=go.Figure(); fig.add_trace(go.Scatter(y=results["equity"], name="Equity")); st.plotly_chart(fig, use_container_width=True)\n    st.dataframe(weights.tail(10))\n''',
'app/main.py':'''from __future__ import annotations\nimport streamlit as st\nfrom app.config import Config\nfrom app.data import load_universe, download_ohlcv, download_benchmark\nfrom app.signals import compute_features, score_frame\nfrom app.regime import market_regime\nfrom app.portfolio import build_portfolio\nfrom app.backtest import run_backtest\nfrom app.scanner import weekly_universe_update\nfrom app.ui import render\n\ndef render_app():\n    st.set_page_config(page_title="Gemini-like Portfolio", layout="wide")\n    cfg=Config()\n    universe=load_universe()\n    selected=st.sidebar.multiselect("Universe", universe["ticker"].tolist(), default=universe["ticker"].head(200).tolist())\n    period=st.sidebar.selectbox("History", ["2y","3y","5y"], index=2)\n    max_positions=st.sidebar.slider("Max positions", 5, 40, cfg.max_positions)\n    if st.sidebar.button("Run full pipeline"):\n        close, vol = download_ohlcv(selected, period=period)\n        qqq = download_benchmark("QQQ", period=period).reindex(close.index).ffill()\n        feats = compute_features(close, vol)\n        score_ts = {}\n        for t, df in feats.items():\n            score_ts[t]=score_frame(df)\n        scores = __import__("pandas").DataFrame(score_ts)\n        regime = market_regime(qqq)\n        weights = build_portfolio(scores, regime, max_positions=max_positions)\n        results = run_backtest(close, weights, cfg.slippage_bps, cfg.fee_bps)\n        latest = scores.iloc[-1]\n        updated, add, remove = weekly_universe_update(latest, selected)\n        render(results, weights, selected, add, remove)\n''',
'pages/1_Overview.py':'''import streamlit as st\nst.write("Overview page")\n''',
'pages/2_Research.py':'''import streamlit as st\nst.write("Research page")\n''',
'pages/3_Scanner.py':'''import streamlit as st\nst.write("Scanner page")\n''',
'tests/test_smoke.py':'''def test_smoke():\n    assert True\n''',
'scripts/run_weekly_scan.py':'''from app.data import load_universe\nprint(load_universe().head())\n'''
}
for rel, content in files.items():
    path=base/rel; path.parent.mkdir(parents=True, exist_ok=True); path.write_text(content)
print(base)
